kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "spring-cloud-k8s-issue.fullname" . }}
data:
  application.yml: |-
    spring:
      application:
        name: {{ include "spring-cloud-k8s-issue.fullname" . }}
  {{- toYaml .Values.config | nindent 4 }}
