kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "spring-cloud-k8s-issue.fullname" . }}-role
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "spring-cloud-k8s-issue.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "spring-cloud-k8s-issue.serviceAccountName" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "spring-cloud-k8s-issue.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
