name: Test Helm Chart

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-chart:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Set up Helm
        uses: azure/setup-helm@v1.1
        with:
          version: v3.5.3

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Provision Kubernetes KinD Cluster and local Container Registry
        uses: container-tools/kind-action@v1

      - name: Build, package and push container image
        run: |
          ./mvnw --batch-mode install \
            jib:build \
            -Djib.to.image=kind-registry:5000/org.rm3l/sck8s-issue-target-class-proxies:latest \
            -Djib.allowInsecureRegistries=true

      - name: Make scripts executable
        run: chmod +x .github/scripts/*.sh

      - name: Install the Helm Release
        run: .github/scripts/install-helm-chart.sh

      - name: Test Helm Release
        run: .github/scripts/test-helm-release.sh
